### ISSUE TITLE
ckanext-rq required for ckanext-validation but not in requirements.txt

### ISSUE THREAD

**Issue by napulen** [mat3rial-dev/YYC-dev#14]
At first, it appeared this was the problem for "hanging" command line validations

**Comment by napulen** [comment]
It only affects ckan_version <= 2.6, it should be fine in our case.

The real problem is that you need to pull the queued jobs through ```jobs```

This works for running command line validations
```
cd /usr/lib/ckan/default/src/ckanext-validation
paster validation run -c /etc/ckan/default/production.ini
paster --plugin=ckan jobs worker -c /etc/ckan/default/production.ini
```
The last command pulls the pending jobs and runs the validation

**Comment by vigliensoni** [comment]
Does this mean that we should have the validation running? Another task
running under supervisor?
​

**Comment by napulen** [comment]
Not if the runtime validator works, but so far it is crashing in the other
issue I mentioned today
