### ISSUE TITLE
CKAN can't write in folder after installing DCAT Harvester

### ISSUE THREAD

**Issue by vigliensoni** [mat3rial-dev/YYC-dev#5]
After installing DCAT harvester, CKAN can't write in a specific folder:
```
 [wsgi:error] [pid 2594:tid 140540254762752] [remote 127.0.0.1:3873]     with open(dest_filename, u'w') as f:
 [wsgi:error] [pid 2594:tid 140540254762752] [remote 127.0.0.1:3873] IOError: [Errno 13] Permission denied: u'/usr/lib/ckan/default/src/ckan/ckan/public/base/i18n/ca.js'
```
Hack for now was allowing 777, but this should be investigated and changed for deployment

**Comment by napulen** [comment]
This is the same problem that ckanext-validation is having when it is being installed from the source.

I also found that their tests search for 
```../ckan/test-core.ini``` 
which is located at 
```/usr/lib/ckan/default/src/ckan/test-core.ini```

So maybe any plugin's source should be placed at
```/usb/lib/ckan/default/src```
if not specified, as a good practice
